AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  StackName:
    Type: 'String'

  DBUsername:
    Type: 'String'
    Default: 'mastodon'

  DBPassword:
    NoEcho: true
    Type: 'AWS::SSM::Parameter::Value<String>'

Resources:
  RdsSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties: 
      DBSubnetGroupDescription: !Sub '${AWS::StackName} subnet group'
      SubnetIds: { 'Fn::Split': [',', {'Fn::ImportValue': !Sub '${StackName}-PrivateSubnetIds'} ]}

  RdsInstancePostgres:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 50
      DBName: 'mastodon'
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DBInstanceClass: 'db.t2.medium'
      DBInstanceIdentifier: !Sub 'rds-${StackName}-pg'
      Engine: 'postgres'
      DBSubnetGroupName: !Ref RdsSubnetGroup
      VPCSecurityGroups:
        - Fn::ImportValue: !Sub '${StackName}-SecurityGroupPostgres'
      Tags:
        - Key: 'Name'
          Value: !Sub 'rds-${AWS::StackName}-pg'

Outputs:
  PostgresAddress:
    Value: !GetAtt RdsInstancePostgres.Endpoint.Address
    Export:
      Name: !Sub '${StackName}-PostgresAddress'

  PostgresPort:
    Value: !GetAtt RdsInstancePostgres.Endpoint.Port
    Export:
      Name: !Sub '${StackName}-PostgresPort'
